#include <iostream>
#include <stack>

using namespace std;

int main() {
    stack<int> s;
        int choice, value;

            do {
                    cout << "\nStack Operations:\n";
                            cout << "[1] Push Data\n";
                                    cout << "[2] Pop Data\n";
                                            cout << "[3] Show Top\n";
                                                    cout << "[4] Show Size\n";
                                                            cout << "[5] Quit\n";
                                                                    cout << "Enter Choice: ";
                                                                            cin >> choice;

                                                                                    switch (choice) {
                                                                                                case 1:
                                                                                                                cout << "Enter value to push: ";
                                                                                                                                cin >> value;
                                                                                                                                                s.push(value);
                                                                                                                                                                break;
                                                                                                                                                                            case 2:
                                                                                                                                                                                            if (!s.empty()) {
                                                                                                                                                                                                                cout << "Popped: " << s.top() << endl;
                                                                                                                                                                                                                                    s.pop();
                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                        cout << "Stack is empty!" << endl;
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                    case 3:
                                                                                                                                                                                                                                                                                                                                    if (!s.empty()) {
                                                                                                                                                                                                                                                                                                                                                        cout << "Top Element: " << s.top() << endl;
                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                            cout << "Stack is empty!" << endl;
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                            break;
                                                                                                                                                                                                                                                                                                                                                                                                                                        case 4:
                                                                                                                                                                                                                                                                                                                                                                                                                                                        cout << "Stack Size: " << s.size() << endl;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 5:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    cout << "Exiting...\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                default:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                cout << "Invalid choice! Try again.\n";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } while (choice != 5);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }